site_name: Gabe Builds Wiki
site_url: https://gabeinvents.github.io/Gabe-Builds-Wiki/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.follow
    - navigation.top
    - navigation.expand
    - search.suggest
    #- search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

  language: en
  palette:
    - scheme: slate # Dark Mode Pallette is default
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: indigo
      accent: lime
    - scheme: default # Light Mode Pallette is a toggleable option
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode    
      primary: blue
      accent: deep purple

  icon:
    tag:
      HTML: fontawesome/brands/html5
      JS: fontawesome/brands/js
      CSS:  fontawesome/brands/css3

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - tables
  - md_in_html
  - attr_list

nav:
  - Home: index.md
  - DRV8825 Breakout Board:
    - DRV8825 Breakout Board\Introduction.md
    - Quick Start: DRV8825 Breakout Board\Quick Start.md
    - Libraries: DRV8825 Breakout Board\libraries.md
    - Microstepping: DRV8825 Breakout Board\microstepping.md
    - Cloning Inputs: DRV8825 Breakout Board\Cloning Inputs.md
  - Tags: tags.md
  - Store: store.md

extra:
  tags:
    HTML5: html
    Javascript: js
    CSS: css
  generator: true

copyright: Copyright &copy; 2024 - 2024, Gabe Builds

plugins:
  - tags:
      tags_file: tags.md
  - search

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css